env:
  es6: true
  commonjs: true
extends: 'eslint:recommended'
globals:
  # LeetCode includes lodash by default (https://leetcode.com/faq/)
  _: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict:
    - error
overrides:
  - files: '*.test.js'
    env:
      node: true
      jest: true
    parserOptions:
      ecmaVersion: 2018
