name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: node --version
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm test -- --coverage
